### ISSUE TITLE
Can't use `/* @@` and ` */` As prefix and suffix?

### ISSUE THREAD

**Issue by SimplGy** [alanshaw/grunt-include-replace#15]
Mostly looking for confirmation--Is it true that I can't use JS comments to contain my includes?

Works:

```
includereplace:
  options:
    prefix: '<!-- @@'
    suffix: ' -->'
```

Does not work:

```
includereplace:
  options:
    prefix: '/* @@'
    suffix: ' */'
```

Is this because those characters are incompatible with the regex used to find the replacement areas?
